### ISSUE TITLE
Do you think it could work with a search function?

### ISSUE THREAD

**Issue by peeter-t2** [dfreelon/fb_scrape_public#1]
E.g. getting only results matching the term on a page:
https://www.facebook.com/search/str/politics/keywords_search?filters_rp_author=134486075205
or
https://www.facebook.com/search/str/search%2Bterm/keywords_search?filters_rp_author=public-feed

Thanks for sharing the app! :)

**Comment by dfreelon** [comment]
As far as I know, Facebook disabled keyword searching through its API awhile back. If anyone knows differently, point me to the documentation and I'll add it to the script. /DEEN

**Comment by peeter-t2** [comment]
Unfortunately no, I don't think there's a good way to get to it from the graph API. Good luck with other things!
