### ISSUE TITLE
AttributeError: module 'fb_scrape_public' has no attribute 'save_creds'

### ISSUE THREAD

**Issue by MohammadHeydari** [dfreelon/fb_scrape_public#10]
![untitled](https://user-images.githubusercontent.com/7662185/48659411-c86d4180-ea65-11e8-9113-32b7b09bf25f.png)
i can't start the process at all. although i got my client ID, secret ID and access token form facebook

**Comment by dfreelon** [comment]
Facebook disabled app access to its API in April. See the README.
