### ISSUE TITLE
Facebook ID

### ISSUE THREAD

**Issue by MasterOfSalt** [dfreelon/fb_scrape_public#3]
I'm dropping this question here but is not a real bug on your side!
But if I try to scrape comments from a belgian journal fb page, it doesnt scrape a thing.
But if I try your example (barack obama), it works...

is there a difference in pages/persons... ?

**Comment by dfreelon** [comment]
I assume it works on any public page. You could post the specific page(s) you're having trouble with if you'd like further assistance...

**Comment by dfreelon** [comment]
My latest update may fix this; try it and let me know if it works!
