### ISSUE TITLE
This issues happening while installing 

### ISSUE THREAD

**Issue by hemangpar** [dfreelon/fb_scrape_public#5]
![image](https://user-images.githubusercontent.com/35444803/35096441-3c9cde18-fc72-11e7-9211-0e272220b507.png)
please help

**Comment by dfreelon** [comment]
Could you include the entire error message--the end appears to be cut off--and in more readable colors if possible? Thanks

**Comment by hemangpar** [comment]
Hi @dfreelon  Please ignore it. I run cmd with admin privileges and then it installed successfully but now this is coming. I try to run python file but no response, no csv file created,nothing, please help
![image](https://user-images.githubusercontent.com/35444803/35135603-4de1dcb8-fd04-11e7-8f78-fa928321c73e.png)

**Comment by dfreelon** [comment]
I strongly suggest you try the sample code at the bottom of the README.md file, as what you've written above won't work. FSP is built to run inside the Python shell, but if you insist on using the command line, you could try something like:

`python -c "import fb_scrape_public as fsp; obama_posts = fsp.scrape_fb('YourClientID','YourClientSecret',ids='barackobama')"`

**Comment by hemangpar** [comment]
Thanks a lot Sir. It worked perfectly.
