### ISSUE TITLE
User data

### ISSUE THREAD

**Issue by hemangpar** [dfreelon/fb_scrape_public#6]
@dfreelon Suppose I am scraping a facebook page data and I want the user's data who have posted on that page which I am scraping, like userid, name, age, location etc, can we?

**Comment by dfreelon** [comment]
Most of that info other than names is private, unless you are personally friends with the user, in which case you need to use an access token generated from your personal account (as opposed to from an app). However, in many cases, gender can be inferred from a person's given name and broad ethnic categories from the family name...
