### ISSUE TITLE
urlopen error [SSL: CERTIFICATE_VERIFY_FAILED]

### ISSUE THREAD

**Issue by Altroo** [dfreelon/fb_scrape_public#7]
Hello i've tested this today and i'm getting this error : 

`ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)`

During handling of the above exception, another exception occurred:

`urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)>`

**Comment by dfreelon** [comment]
Just tested it myself and it works on my end. Please provide the code you used, thanks.

**Comment by Altroo** [comment]
```
import fb_scrape_public as fsp
#added my both secret ids + Page id
my_posts = fsp.scrape_fb("ID1", "ID2", ids="PAGEID")
```

works on windows but not on mac.

**Comment by dfreelon** [comment]
Interesting... let me run some tests and get back to you.

**Comment by Altroo** [comment]
The worked version on windows creates csv file but the content is a messy characters as you can see : 

![capture d ecran 2018-02-05 a 14 54 23](https://user-images.githubusercontent.com/30314254/35810719-8e0bd16c-0a84-11e8-8648-b035e07d9f54.png)

**Comment by dfreelon** [comment]
The weird characters are Excel's fault; try looking at it in a plain text editor. As for the messed up delimiters, you're probably using Euro-style CSV with semicolon delimiters. The best way to fix that is probably to dump the Python var holding the data to file yourself using the standard CSV file writing functions configured for Euro-style CSVs.

**Comment by dfreelon** [comment]
As for your Mac problem, can you confirm you are using the exact same Python version on both Windows and Mac?

**Comment by Altroo** [comment]
Yeah same version 3.6, i've used a basic scrap with beautifulsoup to get some data from wikipedia and same thing SSL: CERTIFICATE_VERIFY_FAILED, but when i run it to get data from a local server it works.

**Comment by dfreelon** [comment]
Well at least that confirms your original issue isn't specific to FSP, so I am gonna close this.
